name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # Run when a tag is pushed
  workflow_dispatch:  # Allow manual trigger

jobs:
  docker-build:
    name: Build and Push Docker Image (Multi-Arch)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git info
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags --exact-match 2>/dev/null || echo '')" >> $GITHUB_OUTPUT

      - name: Build and Push (linux/amd64 + linux/arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/terminal-emacs:latest
            ghcr.io/${{ github.repository_owner }}/terminal-emacs:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.tag && format('ghcr.io/{0}/terminal-emacs:{1}', github.repository_owner, steps.vars.outputs.tag) || '' }}
